apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ppon-route
spec:
  host: ppon-mvp-bg.apps.211-34-231-93.nip.io
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ppon
    weight: 100    
  wildcardPolicy: None  
